version: '3.7'

services:
  www:
    build:
      context: ./docker/php-apache
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_web
    ports:
      - ${HTTP_PORT}:80
      - ${WS_PORT}:3000
    environment:
      GIT_AUTHOR_NAME: ${GIT_USER}
      GIT_AUTHOR_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ./docker/config/ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ./docker/config/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ./docker/config/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/data/logs/:/var/logs/
      - ./docker/data/ssh/known_hosts:/root/.ssh/known_hosts
      - ./:/root/repository
      - ./code/symfony:/var/www/symfony
      - ./docker/config/apache/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./docker/config/apache/sites-available/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro